### ISSUE TITLE
[Bug] AP AR Enhanced Table - Numeric value '' Is Not Recognized

### ISSUE THREAD

**Issue by matt-tkachev** [fivetran/dbt_sage_intacct#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I've already opened a ticket with Fivetran Support, and they've asked me to report the bug here as well. So, I'm pasting the ticket text below. We've recently added a dbt transformation package for Sage Intacct in Fivetran, and all individual table transformations have worked, except for one. There is a "sage_intacct__ap_ar_enhanced" transformation that has failed with an error message: "Numeric value '' is not recognized". The error message makes me think that there is a varchar column that has an empty string entry ('') that the Fivetran transformation code is trying to convert to the numeric data type. However, the error message is very short and not insightful enough to realize what column causes this error.

### Relevant error log or model output

```shell
Database Error in model sage_intacct__ap_ar_enhanced (models/sage_intacct__ap_ar_enhanced.sql)
100038 (22018): Numeric value '' is not recognized
compiled Code at target/run/sage_intacct/models/sage_intacct__ap_ar_enhanced.sql
```

### Expected behavior

"SAGE__INTACCT_AP_AR_ENHANCED" table constructed and inserted into in our destination of Snowflake.

### dbt Project configurations
```yml
config-version: 2
name: 'sage_intacct'
version: '0.2.2'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  sage_intacct:
    +materialized: table
    +schema: sage
    intermediate:
      +materialized: view
vars:
  sage_intacct_database: havenpark
  sage_intacct_schema: sage
  sage_account_pass_through_columns: []
  sage_gl_pass_through_columns: []
  sage_intacct:
    gl_detail: "{{ ref('stg_sage_intacct__gl_detail') }}"
    gl_account: "{{ ref('stg_sage_intacct__gl_account') }}"
    ap_bill_item: "{{ ref('stg_sage_intacct__ap_bill_item') }}"
    ap_bill: "{{ ref('stg_sage_intacct__ap_bill') }}"
    ar_invoice_item: "{{ ref('stg_sage_intacct__ar_invoice_item') }}"
    ar_invoice: "{{ ref('stg_sage_intacct__ar_invoice') }}"
    sage_gl_pass_through_columns: ['location_id', 'location_name']
    sage_account_pass_through_columns: []
    sage_intacct_category_asset: ('Inventory','Fixed Assets','Other Current Assets','Cash and Cash Equivalents','Intercompany Receivable','Accounts Receivable','Deposits and Prepayments','Goodwill','Intangible Assets','Short-Term Investments','Inventory','Accumulated Depreciation','Other Assets','Unrealized Currency Gain/Loss','Patents','Investment in Subsidiary','Escrows and Reserves','Long Term Investments')
    sage_intacct_category_equity: ('Partners Equity','Retained Earnings','Dividend Paid')
    sage_intacct_category_expense: ('Advertising and Promotion Expense','Other Operating Expense','Cost of Sales Revenue', 'Professional Services Expense','Cost of Services Revenue','Payroll Expense','Payroll Taxes','Travel Expense','Cost of Goods Sold','Other Expenses','Compensation Expense','Federal Tax','Depreciation Expense')
    sage_intacct_category_liability: ('Accounts Payable','Other Current Liabilities','Accrued Liabilities','Note Payable - Current','Deferred Taxes Liabilities - Long Term','Note Payable - Long Term','Other Liabilities','Deferred Revenue - Current')
    sage_intacct_category_revenue: ('Revenue','Revenue - Sales','Dividend Income','Revenue - Other','Other Income','Revenue - Services','Revenue - Products')
    sage_intacct__using_invoices: true
    sage_intacct__using_bills: true
analysis-paths: ["analysis"]
```
### Package versions

packages:
- package: fivetran/sage_intacct_source
  version: [">=0.2.0", "<0.3.0"]

### What database are you using dbt with?

snowflake

### dbt Version

dbtVersion: 1.3.0
jobs:
- name: daily
  schedule: 0 8 * * *
  steps:
     - name: run models
       command: dbt run

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
